---
# Default variables for base role

base_packages:
  - wget
  - git
  - zsh
  - gpg
  - zip
  - unzip
  - vim
  - jq
  - telnet
  - curl
  - htop
  - btop
  - python3
  - python3-pip
  - eza
  - micro
  - apt-transport-https
  - zlib1g
  - sqlite3
  - fzf
  - sudo
